[package]
name = "test-bin"
version = "0.1.0"
authors = ["Nate Mara <nate@onesignal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-pkg = { version = "0.2", registry = "nate-mara-alt-crates" }